spring:
    datasource:
        username: thais
        password: 123trocar
        url: jdbc:mysql://pridedevdatabase.c3lbe0bvk2jp.us-east-1.rds.amazonaws.com/thais
    jpa:
        hibernate:
            ddl-auto: update
            
            
